import { ConfigContext, ExpoConfig } from 'expo/config'
import { existsSync } from 'fs'

// Production builds receive Firebase config through project-scoped EAS file variables with
// Sensitive visibility. EAS materialises each uploaded file and exposes its path through the
// matching process.env value. Local, development, and preview builds fall back to the gitignored
// root files generated by `npm run setup:firebase`.
const googleServicesJsonPath = process.env.GOOGLE_SERVICES_JSON ?? './google-services.json'
const googleServiceInfoPlistPath =
  process.env.GOOGLE_SERVICE_INFO_PLIST ?? './GoogleService-Info.plist'

if (!process.env.GOOGLE_SERVICES_JSON && !existsSync(googleServicesJsonPath)) {
  console.warn(
    '\n⚠️  google-services.json not found locally and no EAS file env var resolved.\n' +
      '   Run `npm run setup:firebase`, or place the matching Firebase file in the project root.\n'
  )
}
if (!process.env.GOOGLE_SERVICE_INFO_PLIST && !existsSync(googleServiceInfoPlistPath)) {
  console.warn(
    '\n⚠️  GoogleService-Info.plist not found locally and no EAS file env var resolved.\n' +
      '   Run `npm run setup:firebase`, or place the matching Firebase file in the project root.\n'
  )
}

export default ({ config }: ConfigContext): ExpoConfig => {
  const variant = process.env.APP_VARIANT ?? 'development'
  const isProd = variant === 'production'
  const nameSuffix = isProd ? '' : variant === 'development' ? ' (Dev)' : ' (Preview)'

  return {
    ...config,
    name: `${config.name}${nameSuffix}`,
    ios: {
      ...config.ios,
      googleServicesFile: googleServiceInfoPlistPath,
      infoPlist: {
        ...config.ios?.infoPlist,
        ...(variant === 'development' && {
          // For Firebase emulator debugging from real devices (dev only)
          NSAppTransportSecurity: {
            NSAllowsLocalNetworking: true,
            NSAllowsArbitraryLoads: true,
          },
        }),
      },
    },
    android: {
      ...config.android,
      googleServicesFile: googleServicesJsonPath,
    },
  } as ExpoConfig
}
