import { Currencies, type CurrencyCode } from '@/constants/currencies'

/**
 * Maps ISO 3166-1 alpha-2 region codes to ISO 4217 currency codes.
 * Only includes mappings for currencies that exist in the app's Currencies constant.
 */
const REGION_TO_CURRENCY: Record<string, string> = {
  // Americas
  US: 'USD',
  CA: 'CAD',
  MX: 'MXN',
  BR: 'BRL',
  AR: 'ARS',
  CL: 'CLP',
  CO: 'COP',
  PE: 'PEN',
  UY: 'UYU',
  PY: 'PYG',
  BO: 'BOB',
  VE: 'VEF',
  EC: 'USD',
  GY: 'GYD',
  SR: 'SRD',
  PA: 'PAB',
  CR: 'CRC',
  GT: 'GTQ',
  HN: 'HNL',
  NI: 'NIO',
  SV: 'SVC',
  BZ: 'BZD',
  CU: 'CUP',
  DO: 'DOP',
  HT: 'HTG',
  JM: 'JMD',
  TT: 'TTD',
  BS: 'BSD',
  BB: 'BBD',
  BM: 'BMD',
  KY: 'KYD',
  FK: 'FKP',
  AW: 'AWG',

  // Europe – Eurozone
  DE: 'EUR',
  FR: 'EUR',
  IT: 'EUR',
  ES: 'EUR',
  PT: 'EUR',
  NL: 'EUR',
  BE: 'EUR',
  AT: 'EUR',
  IE: 'EUR',
  FI: 'EUR',
  GR: 'EUR',
  LU: 'EUR',
  SK: 'EUR',
  SI: 'EUR',
  EE: 'EUR',
  LV: 'EUR',
  LT: 'EUR',
  CY: 'EUR',
  MT: 'EUR',
  HR: 'EUR',

  // Europe – Non-Eurozone
  GB: 'GBP',
  CH: 'CHF',
  SE: 'SEK',
  NO: 'NOK',
  DK: 'DKK',
  PL: 'PLN',
  CZ: 'CZK',
  HU: 'HUF',
  RO: 'RON',
  BG: 'BGN',
  RS: 'RSD',
  UA: 'UAH',
  BY: 'BYN',
  RU: 'RUB',
  IS: 'ISK',
  BA: 'BAM',
  MK: 'MKD',
  MD: 'MDL',
  AL: 'ALL',
  GE: 'GEL',
  GI: 'GIP',
  TR: 'TRY',

  // Asia
  JP: 'JPY',
  CN: 'CNY',
  KR: 'KRW',
  IN: 'INR',
  ID: 'IDR',
  TH: 'THB',
  VN: 'VND',
  PH: 'PHP',
  MY: 'MYR',
  SG: 'SGD',
  TW: 'TWD',
  HK: 'HKD',
  MO: 'MOP',
  BD: 'BDT',
  PK: 'PKR',
  LK: 'LKR',
  NP: 'NPR',
  MM: 'MMK',
  KH: 'KHR',
  LA: 'LAK',
  MN: 'MNT',
  KZ: 'KZT',
  UZ: 'UZS',
  KG: 'KGS',
  TJ: 'TJS',
  TM: 'TMT',
  AZ: 'AZN',
  AM: 'AMD',
  BN: 'BND',
  BT: 'BTN',
  MV: 'MVR',
  KP: 'KPW',
  IL: 'ILS',
  JO: 'JOD',
  LB: 'LBP',
  SY: 'SYP',
  IQ: 'IQD',
  IR: 'IRR',

  // Middle East & Gulf
  AE: 'AED',
  SA: 'SAR',
  QA: 'QAR',
  KW: 'KWD',
  BH: 'BHD',
  OM: 'OMR',
  YE: 'YER',

  // Africa
  ZA: 'ZAR',
  NG: 'NGN',
  EG: 'EGP',
  KE: 'KES',
  GH: 'GHS',
  TZ: 'TZS',
  UG: 'UGX',
  ET: 'ETB',
  RW: 'RWF',
  MG: 'MGA',
  MU: 'MUR',
  SC: 'SCR',
  MA: 'MAD',
  DZ: 'DZD',
  TN: 'TND',
  LY: 'LYD',
  SD: 'SDG',
  ER: 'ERN',
  DJ: 'DJF',
  SO: 'SOS',
  MZ: 'MZN',
  ZM: 'ZMW',
  MW: 'MWK',
  NA: 'NAD',
  BW: 'BWP',
  LS: 'LSL',
  SZ: 'SZL',
  LR: 'LRD',
  SL: 'SLL',
  GM: 'GMD',
  GN: 'GNF',
  BI: 'BIF',
  CV: 'CVE',
  ST: 'STN',
  MR: 'MRU',
  AO: 'AOA',
  CD: 'CDF',
  SS: 'SSP',

  // CFA Franc zones
  CM: 'XAF',
  CF: 'XAF',
  TD: 'XAF',
  CG: 'XAF',
  GQ: 'XAF',
  GA: 'XAF',
  SN: 'XOF',
  ML: 'XOF',
  BF: 'XOF',
  CI: 'XOF',
  NE: 'XOF',
  TG: 'XOF',
  BJ: 'XOF',
  GW: 'XOF',

  // Oceania
  AU: 'AUD',
  NZ: 'NZD',
  FJ: 'FJD',
  PG: 'PGK',
  SB: 'SBD',
  VU: 'VUV',
  WS: 'WST',
  TO: 'TOP',
  KM: 'KMF',

  // East Caribbean Dollar
  AG: 'XCD',
  DM: 'XCD',
  GD: 'XCD',
  KN: 'XCD',
  LC: 'XCD',
  VC: 'XCD',

  // CFP Franc
  PF: 'XPF',
  NC: 'XPF',
  WF: 'XPF',
}

export const getCurrencyCodeForRegion = (regionCode: string): CurrencyCode | null => {
  const currencyCode = REGION_TO_CURRENCY[regionCode.toUpperCase()]
  if (!currencyCode) return null
  return currencyCode in Currencies ? (currencyCode as CurrencyCode) : null
}
